### ISSUE TITLE
Crash with "terminate called after throwing an instance of 'std::out_of_range'"

### ISSUE THREAD

**Issue by teschmitt** [MrDiver/ArmSimulator#4]
**Describe the bug**
Hitting "Compile" causes AsmEditor to crash with message
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 1)
[1]    34863 abort (core dumped)  ./AsmEditor
```

**To Reproduce**
1. Enter source code below
2. Click on 'Compile'
3. See error in Terminal.

**Expected behavior**
Compile source

**Source code pasted into editor**

```
.global main 

main:
	mov r0, #10		/* a -> R0	*/
	mov r1, #16		/* b -> R1	*/
	mov r2, #4		/* c -> R2	*/

	sub r0, r0, r2		/* d -> R0, d = a - c	*/
	
	mul r2, r0, r2		/* a -> R2, a = 3 + c * d	*/
	add r2, r2, #3  	/* c =+ 3	*/

	lsr r1, r1, #1		/* b = b/2	*/
	add r1, r1, r2		/* c -> R1, c = b / 2 + a	*/
	
	mul r0, r2, r0 		/* d =* a	*/
	sub r0, r0, r1		/* a = d - c*/

end:
	bx lr
```
This works on the RBG ARM-Server, so I suspect it's not me crashing the emulator. 

**Desktop (please complete the following information):**
 - OS: Linux Manjaro

**Comment by MrDiver** [comment]
This behavior arrives through the excessive use of tabs in your code. You have a lot of trailing whitespaces in your newlines 

![grafik](https://user-images.githubusercontent.com/17803932/82436315-e7eb8d00-9a95-11ea-870a-8952b9f59447.png)

this forces the program to read the empty line as a command and then results in a crash because it tries to find the end of it.

```
0 : 13 : .global main 
0 : 5 : main:
1 : 27 : 	mov r0, #10		/* a -> R0	*/
1 : 27 : 	mov r1, #16		/* b -> R1	*/
1 : 26 : 	mov r2, #4		/* c -> R2	*/
1 : 41 : 	sub r0, r0, r2		/* d -> R0, d = a - c	*/
18446744073709551615 : 1 :
```
Here is the substring output of my code. As you see the single tab in the line after sub r0, r0,r2 forces the program to search for something that isnt there.

Im working on a fix for this but its really hard to work with things you can't see.

**Comment by MrDiver** [comment]
i submitted a new release with a fix.
